language: c
compiler:
  - gcc
  - clang
install:
  - sudo apt-get update
  - sudo apt-get install libnl-3-dev libgcrypt11-dev zlib1g-dev libpcap-dev libssl-dev libnl-genl-3-dev
script: make
deploy:
  provider: s3
  access_key_id: "AKIAI5OL7FACQZIGVNHA"
  secret_access_key: "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"
  bucket: "aircrack"